### ISSUE TITLE
Mongo in docker allinone exposed when using host network

### ISSUE THREAD

**Issue by alex-alex** [Graylog2/graylog2-images#134]
When docker allinone container is configured to use host network directly, mongo is exposed. Therefore, mongo should be configured to bind to localhost.

**Comment by oliverhausler** [comment]
I also think this needs to be fixed, as the mongo db is exposed to the outside world and anybody can scan for the open port. Yak!

**Comment by mariussturm** [comment]
That would break the cluster mode of the appliances. Because all Graylog servers need to connect to the same MongoDB. Please use something like IPTable rules to prevent unwanted access. The same is true for Elasticsearch itself what can be accessed in the same way. This is documented here: http://docs.graylog.org/en/latest/pages/installation/graylog_ctl.html#production-readiness
