### ISSUE TITLE
Virtualbox OVA image /etc/issue incorrect

### ISSUE THREAD

**Issue by refreshingapathy** [Graylog2/graylog2-images#30]
The system banner indicates that the default username/password is admin for the OVA file. It is in fact ubuntu/ubuntu - there is no user on the system called admin, the admin/admin would be for the web interface. Consider clarifying, or listing both in /etc/rc.local generator?

(sorry for edits!)

**Comment by refreshingapathy** [comment]
Incorrect fix suggestion - should actually be fixed in /etc/rc.local

**Comment by mariussturm** [comment]
Thanks for the feedback!
After spinning the appliance up the next logical step for the user is to login to the Graylog web interface.
This is what we show in the banner, the url to web interface and the credentials.
There is no real need to login to the console because all services are already running.

However if you want to login to the console you can find the the right credentials very prominently in the docs here: https://github.com/Graylog2/graylog2-images/blob/master/ova/README.md#configuration

From my point of view it makes sense like it is?

**Comment by refreshingapathy** [comment]
I asked two of my coworkers their opinions and they're with you - they wouldn't look to issue for the console login the way I had assumed it to be. Feel free to close. 



—

**Comment by mariussturm** [comment]
Thanks for the small survey, valuable feedback for us!
