### ISSUE TITLE
maybe add docs about env settings overlap : -port in GRAYLOG_SMTP_SERVER == won't start

### ISSUE THREAD

**Issue by sheavner** [Graylog2/graylog2-images#60]
I haven't dug through the sources to see how the environment variables are used, but I screwed up some cutting and pasting and had a -port with only one minus in GRAYLOG_SMTP_SERVER.   Maybe mongodb or some other process slurped up this setting and started running on port 25.  The cluster wouldn't start and there weren't really any log messages that helped me with the investigation. 

Overall though docker seems a great way to distribute this and the exposed settings have covered everything I've needed.  Nice job.

**Comment by scorpp** [comment]
Similar issue here -  a docker container was set up without smtp setting specified first. Afterwards we needed alerts, but adding GRAYLOG_SMTP_SERVER has no effect

**Comment by mariussturm** [comment]
I improved the options parsing for GRAYLOG_SMTP_SERVER a little bit. Now the command should fail if you provide `-port` instead of `--port`. Same goes for a missing SMTP server like `"localhost --port=25"` vs. `"--port=25"`.

@scorpp if you change something on the container settings you need to recreate the container. Use the data persist option for this: http://docs.graylog.org/en/latest/pages/installation/docker.html#persist-data
Then it's easy to start a new container with changed options on-top of old data.
