### ISSUE TITLE
api-browser not support in Docker

### ISSUE THREAD

**Issue by winggundamth** [Graylog2/graylog2-images#88]
I'm using allinone Docker Image. When I open api-browser the ip adress will be the ip of Docker container. I have to edit /opt/graylog/embedded/cookbooks/graylog/templates/default/graylog.conf.erb file to set rest_transport_uri variable and doing graylog-ctl reconfigure.

Docker image should support assign rest_transport_uri variable with domain or ipaddress.

**Comment by mariussturm** [comment]
This is currently not possible because changing the listen address for the REST API would lead to broken cluster mode. What you can do is to start the Docker container with a port forward for port 12900, like: `docker run -t -p 9000:9000 -p 12201:12201 -p 12900:12900 graylog2/allinone` and access the api browser directly by using the host ip. `open http://localhost:12900` or whatever your host ip is.

**Comment by winggundamth** [comment]
Just want to let you know that if I don't configure it. When I open api-browser it will alway show this error as in image. And Try it out! button won't work in Swagger.

![2558-09-16 20_46_32-the page at 172 24 12 5_12900 says_](https://cloud.githubusercontent.com/assets/4833238/9906468/7414c906-5cb4-11e5-8df8-d7b14ffb35cb.png)

**Comment by mariussturm** [comment]
Yes, this is exactly the problem. When you try to test an api call through Swagger, it tries to connect to 172.24.12.5. But the internal container IP is not reachable from the outside so Swagger can not know where to connect to. By changing the `rest_listen_uri` you can work around this but at the same time you can break Graylog's cluster mode. A second Graylog server would then not be able to talk to this container anymore.
So at the moment you can access the api browser but read-only.
